apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: db-storage-coffeeshop
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
parameters:
  type: gp3 
  encrypted: "true"
volumeBindingMode: WaitForFirstConsumer 
reclaimPolicy: Delete 
allowVolumeExpansion: true 