apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service
  namespace: coffeeshop-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-service
  template:
    metadata:
      labels:
        app: web-service
    spec:
      containers:
        - name: web
          image: cuongopswat/go-coffeeshop-web
          ports:
            - containerPort: 8888
          env:
            - name: REVERSE_PROXY_URL
              value: http://proxy-service:5000
            - name: WEB_PORT
              value: "8888"