apiVersion: apps/v1
kind: Deployment
metadata:
  name: barista-service
  namespace: coffeeshop-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barista-service
  template:
    metadata:
      labels:
        app: barista-service
    spec:
      containers:
        - name: barista
          image: ttvucse/devops_training:go-coffeeshop-barista
          envFrom:
            - configMapRef:
                name: app-config
            - configMapRef:
                name: postgres-config
            - configMapRef:
                name: rabbitmq-config
            - secretRef:
                name: postgres-secret
            - secretRef:
                name: rabbitmq-secret
          env:
            - name: IN_DOCKER
              value: "true"
            - name: RABBITMQ_URL
              value: "amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@$(RABBITMQ_HOST):$(RABBITMQ_PORT)"
      imagePullSecrets:
        - name: dockerhub-secret