apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: coffeeshop-prod
type: kubernetes.io/dockerconfigjson
data:
  # The following is a base64 encoded version of the docker config JSON
  # that contains the Docker Hub credentials. You can generate this using json file:
  # {
  #   "auths": {
  #     "https://index.docker.io/v1/": {
  #       "username": "user",
  #       "password": "pass",
  #       "email": "user@example.com",
  #       "auth": "dXNlcjpwYXNz"
  #     }
  #   }
  # }
  # .dockerconfigjson = cat config.json | base64 -w 0

  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICJ1c2VybmFtZSI6ICJ0dHZ1Y3NlIiwKICAgICAgInBhc3N3b3JkIjogImRja3JfcGF0X1UyN29CdE9wOHJPR2VTalM0Z2hNTjQtQjNQYyIsCiAgICAgICJlbWFpbCI6ICJ0dHZ1Y3NlQGdtYWlsLmNvbSIsCiAgICAgICJhdXRoIjogImRIUjJkV056WlRwa1kydHlYM0JoZEY5Vk1qZHZRblJQY0RoeVQwZGxVMnBUTkdkb1RVNDBMVUl6VUdNPSIKICAgIH0KICB9Cn0K
