apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: coffeeshop-web-hpa
  namespace: coffeeshop-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: coffeeshop-web
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70 # scale up when the average CPU utilization exceeds 70%
  - type: External
    external:
      metric:
        name: requests_per_second
        selector:
          matchLabels:
            app: coffeeshop-web
      target:
        type: AverageValue
        averageValue: 100 # scale up when the average requests per second exceeds 100