apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-service
  namespace: coffeeshop-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-service
  template:
    metadata:
      labels:
        app: counter-service
    spec:
      containers:
        - name: counter
          image: cuongopswat/go-coffeeshop-counter
          ports:
            - containerPort: 5002
          envFrom:
            - configMapRef:
                name: app-config
            - configMapRef:
                name: postgres-config
            - configMapRef:
                name: rabbitmq-config
            - secretRef:
                name: postgres-secret
            - secretRef:
                name: rabbitmq-secret
          env:
            - name: IN_DOCKER
              value: "true"
            - name: PRODUCT_CLIENT_URL
              value: product-service:5001
            - name: RABBITMQ_URL
              value: "amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@$(RABBITMQ_HOST):$(RABBITMQ_PORT)"
      imagePullSecrets:
        - name: dockerhub-secret
