apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: coffeeshop-prod
spec:
  ports:
    - name: amqp  # RabbitMQ main protocol port
      port: 5672
      targetPort: 5672
      protocol: TCP
    - name: management  # RabbitMQ management UI port
      port: 15672
      targetPort: 15672
      protocol: TCP
  selector:
    app: rabbitmq